[mypy]
python_version = 3.9
files = src, scripts
warn_return_any = True
warn_unused_ignores = True
warn_redundant_casts = True
disallow_any_generics = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
strict_equality = True
check_untyped_defs = True

[mypy-plyfile.*]
ignore_missing_imports = True

[mypy-trimesh.*]
ignore_missing_imports = True

[mypy-igl.*]
ignore_missing_imports = True

[mypy-simple_knn.*]
ignore_missing_imports = True

[mypy-diff_gaussian_rasterization.*]
ignore_missing_imports = True

[mypy-tinycudann.*]
ignore_missing_imports = True

[mypy-lpips.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-imageio.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-pytorch3d.*]
ignore_missing_imports = True

[mypy-torchmetrics.image.lpip]
ignore_missing_imports = True

[mypy-skimage.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-mpl_toolkits.*]
ignore_missing_imports = True

[mypy-smplx.*]
ignore_missing_imports = True

[mypy-knn_cuda.*]
ignore_missing_imports = True

[mypy-wandb.*]
ignore_missing_imports = True

[mypy-hydra.*]
ignore_missing_imports = True

[mypy-torchvision]
ignore_missing_imports = True

[mypy-torchvision.*]
ignore_missing_imports = True
